name: Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**' ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Destroy existing resources
      run: terraform destroy -auto-approve -var="public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}" || true
      working-directory: terraform
      continue-on-error: true
    
    - name: Clean state
      run: rm -f terraform.tfstate* .terraform.lock.hcl && rm -rf .terraform/
      working-directory: terraform
    
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -var="public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
      working-directory: terraform